#!/usr/bin/env python3
"""Generate the Windows app's .resw files from shared/localization.

The Windows counterpart of mac/Scripts/merge-translations.py (PLAN.md 18.3,
"Localization"). Reads shared/localization/strings-en.json and the four
translator files (de, es, zh-Hant, zh-Hans; same shape plus "translation")
and writes

    windows/Hearsay.App/Strings/<lang>/Resources.resw     (en, de, es, zh-Hant, zh-Hans)

the layout MRT Core (Microsoft.Windows.ApplicationModel.Resources) indexes
into the app's PRI with the folder name as the language qualifier.

Which keys: every App("..."), Core("...") and Win("...") call in
windows/Hearsay.App/Strings.cs (the catalogs "app", "core" and "windows" of
the JSON files), plus every "core" entry, so Strings.CoreText can translate
the plain English a Core type returns. The generated files are committed, so
a build needs no Python; run this after changing Strings.cs or the JSON files.

Resource names are "<catalog>_" plus the first 16 hex digits of the SHA-256
of the UTF-8 key (keys are English sentences, which resw names cannot hold);
Strings.cs computes the same name. Each entry's comment shows the key.

Values: an entry whose English has placeholders (%@, %lld, %d, %1$@, ...) or
%% becomes a .NET composite format string: braces doubled, %% -> %, plain
placeholders numbered {0}, {1}, ... in order, %n$ -> {n-1}. Any other entry
is written as it is, for Strings.cs to use without string.Format.

Fails, listing every problem, when a key the app uses is missing from
strings-en.json or from any language, when a translation is empty or its
English is stale, when placeholders differ between the English and a
translation, or when Strings.cs formats a text without placeholders (or the
reverse).

Usage, from the repo root:
    python windows/scripts/import-strings.py            # write the .resw files
    python windows/scripts/import-strings.py --check    # CI: verify they are current
"""
import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parents[2]
LOCALIZATION = ROOT / "shared" / "localization"
APP = ROOT / "windows" / "Hearsay.App"
STRINGS_CS = APP / "Strings.cs"
OUTPUT = APP / "Strings"
LANGUAGES = ["en", "de", "es", "zh-Hant", "zh-Hans"]
CALL_CATALOG = {"App": "app", "Core": "core", "Win": "windows"}

# The placeholder rule of mac/Scripts/export-strings.py.
PLACEHOLDER = re.compile(
    r"%(?:(\d+)\$)?[-+ #0']*(?:\d+|\*)?(?:\.(?:\d+|\*))?(?:hh|h|ll|l|q|z|t|j|L)?[@dDuUxXoOfFeEgGcCsSaAp]"
)
FORMAT_TOKEN = re.compile("%%|" + PLACEHOLDER.pattern)
# A call such as App("text"), Win("a" + "b", x): the literals, then what follows.
CALL = re.compile(r'\b(App|Core|Win)\(\s*((?:"(?:[^"\\\n]|\\.)*"\s*(?:\+\s*)?)+)\s*([,)])')
LITERAL = re.compile(r'"((?:[^"\\\n]|\\.)*)"')
CS_ESCAPES = {'"': '"', "\\": "\\", "n": "\n", "t": "\t", "r": "\r", "0": "\0", "'": "'"}

RESW_HEAD = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by windows/scripts/import-strings.py from shared/localization/{source}. Do not edit. -->
<root>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
"""


class ImportError_(Exception):
    pass


def resource_name(catalog, key):
    """Must match Strings.ResourceName in Strings.cs."""
    return f"{catalog}_{hashlib.sha256(key.encode('utf-8')).hexdigest()[:16]}"


def cs_unescape(text):
    out = []
    i = 0
    while i < len(text):
        char = text[i]
        if char != "\\":
            out.append(char)
            i += 1
            continue
        nxt = text[i + 1]
        if nxt == "u":
            out.append(chr(int(text[i + 2:i + 6], 16)))
            i += 6
        elif nxt in CS_ESCAPES:
            out.append(CS_ESCAPES[nxt])
            i += 2
        else:
            raise ImportError_(f"unsupported escape \\{nxt} in Strings.cs")
    return "".join(out)


def strip_comments(source):
    """Blank out // and /* */ comments, keeping string literals."""
    pattern = re.compile(r'"(?:[^"\\\n]|\\.)*"|//[^\n]*|/\*.*?\*/', re.S)
    return pattern.sub(lambda m: m.group(0) if m.group(0).startswith('"') else " " * len(m.group(0)), source)


def scan_strings_cs():
    """{(catalog, key): uses_format} for every App/Core/Win call."""
    source = strip_comments(STRINGS_CS.read_text(encoding="utf-8"))
    used = {}
    problems = []
    for match in CALL.finditer(source):
        catalog = CALL_CATALOG[match.group(1)]
        key = "".join(cs_unescape(part) for part in LITERAL.findall(match.group(2)))
        formats = match.group(3) == ","
        previous = used.get((catalog, key))
        if previous is not None and previous != formats:
            problems.append(f"Strings.cs: {catalog}:{key!r} is used both with and without arguments")
        used[(catalog, key)] = formats
    # Every call must have been a literal the scan understood.
    calls = len(re.findall(r"\b(?:App|Core|Win)\(", source)) - len(re.findall(r"\b(?:private|static|string)\s+(?:App|Core|Win)\(", source))
    found = len(CALL.findall(source))
    if calls != found:
        problems.append(f"Strings.cs: {calls - found} App/Core/Win call(s) do not pass a string literal key; the scan cannot see them")
    return used, problems


def has_format(english):
    return "%%" in english or bool(PLACEHOLDER.search(english.replace("%%", "")))


def placeholder_specs(text):
    """[(position or None, spec without position)]."""
    specs = []
    for match in PLACEHOLDER.finditer(text.replace("%%", "")):
        spec = match.group(0)
        position = int(match.group(1)) if match.group(1) else None
        if position is not None:
            spec = "%" + spec[len(match.group(1)) + 2:]
        specs.append((position, spec))
    return specs


def check_placeholders(english, translation):
    wanted = [spec for _, spec in placeholder_specs(english)]
    got = placeholder_specs(translation)
    positions = [position for position, _ in got]
    if any(position is not None for position in positions):
        if any(position is None for position in positions):
            return "mixes numbered (%1$@) and plain (%@) placeholders"
        if sorted(positions) != list(range(1, len(wanted) + 1)):
            return f"numbered placeholders {sorted(positions)} do not cover 1..{len(wanted)} once each"
        for position, spec in got:
            if wanted[position - 1] != spec:
                return f"%{position}$ is {spec} but the English placeholder is {wanted[position - 1]}"
        return None
    if [spec for _, spec in got] != wanted:
        return f"placeholders {[spec for _, spec in got]} differ from the English {wanted}"
    return None


def to_dotnet(text):
    """A printf-style catalog string as a .NET composite format string."""
    counter = 0
    out = []
    last = 0
    for match in FORMAT_TOKEN.finditer(text):
        out.append(text[last:match.start()].replace("{", "{{").replace("}", "}}"))
        token = match.group(0)
        if token == "%%":
            out.append("%")
        elif match.group(1):
            out.append("{" + str(int(match.group(1)) - 1) + "}")
        else:
            out.append("{" + str(counter) + "}")
            counter += 1
        last = match.end()
    out.append(text[last:].replace("{", "{{").replace("}", "}}"))
    return "".join(out)


def load(name):
    path = LOCALIZATION / name
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise ImportError_(f"{path}: {error}") from error
    if not isinstance(data, list):
        raise ImportError_(f"{path}: must hold a JSON array")
    return data


def build():
    """{lang: resw text}, or raises with every problem."""
    used, problems = scan_strings_cs()
    english_entries = {}
    for entry in load("strings-en.json"):
        english_entries[(entry["catalog"], entry["key"])] = entry
    wanted = dict(used)
    for identity in english_entries:
        if identity[0] == "core":
            wanted.setdefault(identity, None)
    for identity, formats in sorted(used.items()):
        entry = english_entries.get(identity)
        if entry is None:
            problems.append(f"{identity[0]}:{identity[1]!r}: used in Strings.cs but not in strings-en.json")
            continue
        if formats is not None and formats != has_format(entry["english"]):
            kind = "formats" if formats else "does not format"
            problems.append(f"{identity[0]}:{identity[1]!r}: Strings.cs {kind} it, but its English "
                            f"{'has no' if formats else 'has'} placeholders")
    unused = sorted(k for c, k in english_entries if c == "windows" and ("windows", k) not in used)
    translations = {"en": {identity: entry["english"] for identity, entry in english_entries.items()}}
    for lang in LANGUAGES[1:]:
        seen = {}
        for entry in load(f"{lang}.json"):
            identity = (entry.get("catalog"), entry.get("key"))
            if identity not in wanted:
                continue
            english = english_entries[identity]["english"]
            label = f"{lang} {identity[0]}:{identity[1]!r}"
            translation = entry.get("translation")
            if entry.get("english") != english:
                problems.append(f"{label}: the English changed (now {english!r}); translate it again")
            if not isinstance(translation, str) or not translation.strip():
                problems.append(f"{label}: empty translation")
                continue
            if has_format(english):
                problem = check_placeholders(english, translation)
                if problem:
                    problems.append(f"{label}: {problem}")
            seen[identity] = translation
        for identity in sorted(set(wanted) - set(seen)):
            if identity in english_entries:
                problems.append(f"{lang} {identity[0]}:{identity[1]!r}: missing")
        translations[lang] = seen
    if problems:
        raise ImportError_("\n".join(problems))

    files = {}
    for lang in LANGUAGES:
        source = "strings-en.json" if lang == "en" else f"{lang}.json"
        lines = [RESW_HEAD.format(source=source)]
        rows = []
        for identity in wanted:
            catalog, key = identity
            english = english_entries[identity]["english"]
            value = translations[lang][identity]
            if has_format(english):
                value = to_dotnet(value)
            rows.append((resource_name(catalog, key), value, f"{catalog}: {key}"))
        for name, value, comment in sorted(rows):
            lines.append(f'  <data name="{name}" xml:space="preserve">\n'
                         f"    <value>{escape(value)}</value>\n"
                         f"    <comment>{escape(comment)}</comment>\n"
                         f"  </data>\n")
        lines.append("</root>\n")
        files[OUTPUT / lang / "Resources.resw"] = "".join(lines)
    return files, len(used), len(wanted), unused


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="verify the .resw files are current; write nothing")
    args = parser.parse_args()
    try:
        files, used, total, unused = build()
    except ImportError_ as error:
        print(error, file=sys.stderr)
        sys.exit(1)
    for key in unused:
        print(f"note: windows:{key!r} is in strings-en.json but Strings.cs does not use it", file=sys.stderr)
    if args.check:
        stale = [path for path, text in files.items()
                 if not path.exists() or path.read_bytes() != text.encode("utf-8")]
        if stale:
            for path in stale:
                print(f"{path.relative_to(ROOT)} is out of date; run windows/scripts/import-strings.py", file=sys.stderr)
            sys.exit(1)
        print(f"ok: {len(files)} .resw files current ({used} keys used by Strings.cs, {total} entries each)")
        return
    for path, text in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(text.encode("utf-8"))
    print(f"wrote {len(files)} .resw files ({used} keys used by Strings.cs, {total} entries each)")


if __name__ == "__main__":
    main()
