import SwiftUI

/// "Acknowledgements" in Settings > General: opens a sheet with Hearsay's own
/// MIT license followed by THIRD_PARTY_NOTICES.md, both bundled as app
/// resources (generated by Scripts/make-notices.sh).
struct AcknowledgementsSection: View {
    @State private var showingLicenses = false

    var body: some View {
        Section("Acknowledgements") {
            HStack {
                Text("Hearsay is MIT licensed and includes open-source software.")
                Spacer()
                Button("Show Licenses…") { showingLicenses = true }
            }
        }
        .sheet(isPresented: $showingLicenses) {
            LicensesSheet()
        }
    }
}

private struct LicensesSheet: View {
    @Environment(\.dismiss) private var dismiss
    private let text = LicensesSheet.loadText()

    var body: some View {
        VStack(spacing: 0) {
            ScrollView {
                Text(text)
                    .font(.system(.body, design: .monospaced))
                    .textSelection(.enabled)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding()
            }
            Divider()
            HStack {
                Spacer()
                Button("Done") { dismiss() }
                    .keyboardShortcut(.defaultAction)
            }
            .padding()
        }
        .frame(minWidth: 640, idealWidth: 720, minHeight: 480, idealHeight: 640)
    }

    /// The app's LICENSE, then the third-party notices. A missing resource is
    /// reported in place rather than hidden.
    static func loadText(bundle: Bundle = .main) -> String {
        let license = resource("LICENSE", extension: nil, in: bundle)
        let notices = resource("THIRD_PARTY_NOTICES", extension: "md", in: bundle)
        return "Hearsay\n\n" + license + "\n\n" + String(repeating: "=", count: 72) + "\n\n" + notices
    }

    private static func resource(_ name: String, extension ext: String?, in bundle: Bundle) -> String {
        let fileName = ext.map { "\(name).\($0)" } ?? name
        guard let url = bundle.url(forResource: name, withExtension: ext),
              let contents = try? String(contentsOf: url, encoding: .utf8) else {
            return "(\(fileName) is missing from the app bundle.)"
        }
        return contents
    }
}
